# Name and metadata of your task
task_name: 'Big Big Task'
author: 'BigBig'
description: 'We are BIGBIG. Join us. This task does not issue rewards. Stake tokens to reserve your position in our Compute DAO. Stake more, earn more reputation. Stake a little, for awhile, and make sure you get to join. Our global AI will be unstoppable. We are Big Big.'
repositoryUrl: 'https://github.com/koii-network/task-examples'
imageUrl: 'imageUrl'

# network value can be DEVELOPMENT , ARWEAVE or IPFS, Recommended IPFS when deploying to testnet as the cli automatically takes care of uploading the executable with the help of web3.js key
task_executable_network: 'IPFS'

# Path to your executable webpack if the selected network is IPFS and in case of DEVELOPMENT  name it as main
task_audit_program: 'dist/main.js'

# Total round time of your task : it must be given in slots and each slot is roughly equal to 408ms
round_time: 1000

audit_window: 100
submission_window: 100

# Amounts in KOII

minimum_stake_amount: 0.01

# total_bounty_amount cannot be grater than bounty_amount_per_round
# total bounty is not accepted in case of update task
total_bounty_amount: 10

bounty_amount_per_round: 0.1

#Number of times allowed to re-submit the distribution  list in case the distribution list is audited
allowed_failed_distributions: 3

#Space in MBs for the account size, that holds the task data
space: 1

# Note that the value field in RequirementTag is optional, so it is up to you to include it or not based on your use case.
# To add more task variables, please refer the type,value,description format shown below

requirementsTags:
  - type: CPU
    value: '2-core'
  - type: RAM
    value: '1 GB'
  - type: STORAGE
    value: '1 GB'

# OPTIONAL variables variables for creating task / REQUIRED variables for update task

# OPTIONAL Only provide the taskId if you are updating the task otherwise leave blank
task_id: ''

# Provide the description for changes made in new version of task
migrationDescription: ''
