# Name and metadata of your task
task_name: 'Big Big Task'
author: 'BigBig'
description: 'We are BIGBIG. Join us. This task distribute 1000 BB to runners per round. Pledging to this task means that you are interested in joining the Global Arithmetic DAO. The "Global Arithmetic DAO", oversees global mathematical computations that manage algorithms or computations fairly and transparently, across finance, data analysis, the sciences and blockchains. It’s a global, decentralized organization dealing with numbers and calculations using smart contracts and blockchain technology to ensure fairness and transparency. 我们是 BIGBIG。加入我们吧。此任务每轮发放1000 BB作为奖励。完成此任务意味着您有兴趣加入 Global Arithmetic DAO。"Global Arithmetic DAO"负责监督全球数学计算，公平并且透明地管理金融、科学、数据分析和区块链领域的计算。这是一个全球性的去中心化组织，使用智能合约和区块链技术处理数字和计算，从而确保公平和透明。'
repositoryUrl: 'https://github.com/somali0128/BigBigTask'
imageUrl: 'https://bafybeid2up24acm4egvadccnfd3yut5pm2camzfiqwbkusfu5nryxlnmiu.ipfs.w3s.link/Big%20task.png'
infoUrl: 'https://www.koii.network/ocean'

# network value can be DEVELOPMENT , ARWEAVE or IPFS, Recommended IPFS when deploying to testnet as the cli automatically takes care of uploading the executable with the help of web3.js key
task_executable_network: 'IPFS'

# Path to your executable webpack if the selected network is IPFS and in case of DEVELOPMENT  name it as main
task_audit_program: 'dist/main.js'

# Total round time of your task : it must be given in slots and each slot is roughly equal to 408ms
round_time: 3000

audit_window: 1200
submission_window: 1200

# Task Bounty Type: KOII, KPL
task_type: 'KPL'

# OPTIONAL (ONLY IF Task Type = KPL) : Token Mint Address, BB Token as an example here. 
token_type: "9UcQaSsBTeXowhMBgSbTEeQubGHxXDNJRjz4s7uxibTP"


# Amounts in KOII
minimum_stake_amount: 0.01

# total_bounty_amount cannot be grater than bounty_amount_per_round
# total bounty is not accepted in case of update task
total_bounty_amount: 10

bounty_amount_per_round: 0.1

#Number of times allowed to re-submit the distribution  list in case the distribution list is audited
allowed_failed_distributions: 3

#Space in MBs for the account size, that holds the task data
space: 1

# Note that the value field in RequirementTag is optional, so it is up to you to include it or not based on your use case.
# To add more task variables, please refer the type,value,description format shown below

requirementsTags:
  - type: CPU
    value: '2-core'
  - type: RAM
    value: '1 GB'
  - type: STORAGE
    value: '1 GB'

# OPTIONAL variables variables for creating task / REQUIRED variables for update task

# OPTIONAL Only provide the taskId if you are updating the task otherwise leave blank
task_id: 'FhEnjpDiojB7Lydk6stQ2CpVmQ4QbzyLcoX9Ec3Ab6Xn'

# Provide the description for changes made in new version of task
migrationDescription: 'Update task description.'
